-- Create a database called philly_travel if it doesn't already exist
CREATE DATABASE IF NOT EXISTS philly_travel;

-- Use the philly_travel database
USE philly_travel;
-- Drop the places table if it already exists
DROP TABLE IF EXISTS places;
-- Create a new places table with appropriate data types
CREATE TABLE places (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    picture_url VARCHAR(512),
    address VARCHAR(255) NOT NULL,
    tripadvisor_rating DECIMAL(3, 1)
);
-- Insert data into the places table
INSERT INTO places (name, description, picture_url, address, tripadvisor_rating) VALUES
('American Philosophical Society', 'Prominent scholarly organization dedicated to the advancement of knowledge in science, humanities, and social sciences.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/American_Philosophical_Society_%2820864173941%29.jpg/1920px-American_Philosophical_Society_%2820864173941%29.jpg', '104 S. Fifth Street, Philadelphia', 4.5),
('Benjamin Franklin National Memorial', 'Commemorative statue and memorial hall honoring the life and achievements of Benjamin Franklin.', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Benjamin_Franklin_National_Memorial.jpg', '222 N. 20th Street, Philadelphia', 4.5),
('Betsy Ross House', 'Historic home turned museum where Betsy Ross is believed to have sewn the first American flag.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Betsy_Ross_House_239_Arch_Street.jpg/1920px-Betsy_Ross_House_239_Arch_Street.jpg', '239 Arch Street, Philadelphia', 4.0),
('Congress Hall', 'Historic building serving as the seat of the United States Congress from 1790 to 1800.', 'https://upload.wikimedia.org/wikipedia/commons/4/47/Congress_Hall_exterior.jpg', '6th & Chestnut Streets, Philadelphia', 4.5),
('Elfreth''s Alley', 'America''s oldest residential street, offering a glimpse into colonial-era architecture and lifestyle.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Elfreth%27s_Alley_2.JPG/1920px-Elfreth%27s_Alley_2.JPG', 'Between 2nd and Front Streets, Philadelphia', 4.5),
('Fairmount Water Works', 'Historic waterworks complex and interpretive center showcasing early engineering and water supply technology.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Fairmount_Water_Works_LOC_314409cu.jpg/1920px-Fairmount_Water_Works_LOC_314409cu.jpg', '640 Waterworks Drive, Philadelphia', 4.5),
('First Bank of the United States', 'Historic bank building serving as the nation''s first central bank from 1791 to 1811.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/First_Bank_of_the_United_States%2C_Philadelphia%2C_Pennsylvania_LCCN2011633532_%28edited%29.jpg/1920px-First_Bank_of_the_United_States%2C_Philadelphia%2C_Pennsylvania_LCCN2011633532_%28edited%29.jpg', '120 S. 3rd Street, Philadelphia', 4.0),
('Franklin Court', 'Site commemorating the life and legacy of Benjamin Franklin with a museum and historic displays.', 'https://upload.wikimedia.org/wikipedia/commons/1/12/Independence_National_Historical_Park-064.jpg', '314 Market Street, Philadelphia', 4.0),
('Gloria Dei (Old Swedes'' Church)', 'Historic church dating back to the 17th century, offering insights into early Swedish settlement in the region.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/2014_Gloria_Dei_%28Old_Swedes%27%29_Church_from_west.jpg/1920px-2014_Gloria_Dei_%28Old_Swedes%27%29_Church_from_west.jpg', '916 S. Swanson Street, Philadelphia', 4.5),
('Independence Hall', 'Historic landmark where the Declaration of Independence and the United States Constitution were debated and adopted.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Exterior_of_the_Independence_Hall%2C_Aug_2019.jpg/1920px-Exterior_of_the_Independence_Hall%2C_Aug_2019.jpg', '520 Chestnut Street, Philadelphia', 4.5),
('Independence National Historical Park', 'National park encompassing numerous historic sites in Philadelphia, including Independence Hall and the Liberty Bell.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Independence_Visitor_Center_Exterior.jpg/1920px-Independence_Visitor_Center_Exterior.jpg', '143 S. Third Street, Philadelphia', 4.5),
('Liberty Bell', 'Iconic symbol of American freedom housed within Independence National Historical Park.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Liberty_Bell_2017a.jpg/1920px-Liberty_Bell_2017a.jpg', '526 Market Street, Philadelphia', 4.5),
('Merchants'' Exchange Building (Philadelphia)', 'Historic building once a vital center for commerce and trade in the city.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Philadelphia_Merchants_Exchange_Building_%2820864134401%29.jpg/1920px-Philadelphia_Merchants_Exchange_Building_%2820864134401%29.jpg', '143 S. Third Street, Philadelphia', 4.0),
('Philadelphia City Hall', 'Iconic government building and architectural landmark housing the city''s government offices.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Philadelphia_city_hall.jpg/1280px-Philadelphia_city_hall.jpg', 'Broad and Market Streets, Philadelphia', 4.5),
('Philadelphia Museum of Art', 'Renowned art museum featuring an extensive collection spanning centuries and cultures.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/PhiladelphiaMuseumOfArt2017.jpg/1920px-PhiladelphiaMuseumOfArt2017.jpg', '2600 Benjamin Franklin Parkway, Philadelphia', 4.5),
('Barnes Foundation', 'Art museum and educational institution known for its impressive collection of Impressionist, Post-Impressionist, and early Modern paintings.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Barnes_Philly_1.JPG/1920px-Barnes_Philly_1.JPG', '2025 Benjamin Franklin Parkway, Philadelphia', 4.5),
('Pennsylvania Academy of the Fine Arts', 'Oldest art museum and school in the United States, showcasing American art from the 18th century to the present.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Pennsylvania_Academy_of_the_Fine_Arts_building.jpg/1920px-Pennsylvania_Academy_of_the_Fine_Arts_building.jpg', '118-128 N. Broad Street, Philadelphia', 4.5),
('Franklin Institute', 'Interactive science museum and educational center offering hands-on exhibits and programs.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Philly042107-010-FranklinInstitute.jpg/1920px-Philly042107-010-FranklinInstitute.jpg', '222 N. 20th Street, Philadelphia', 4.5),
('Mütter Museum', 'Medical museum housing a vast collection of anatomical specimens, medical instruments, and pathological artifacts.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/College_of_Physicians_1.JPG/1920px-College_of_Physicians_1.JPG', '19 S. 22nd Street, Philadelphia', 4.5),
('National Liberty Museum', 'Museum celebrating freedom and diversity, featuring exhibits on civil rights, tolerance, and heroism.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Philadelphia_National_Bank_National_Liberty_Museum_321_Chestnut_Street.jpg/1920px-Philadelphia_National_Bank_National_Liberty_Museum_321_Chestnut_Street.jpg', '321 Chestnut Street, Philadelphia', 4.0),
('Philadelphia History Museum', 'Museum dedicated to preserving and interpreting the history of the city and its residents.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Philadelphia_History_Museum_at_the_Atwater_Kent_from_south.jpg/1920px-Philadelphia_History_Museum_at_the_Atwater_Kent_from_south.jpg', '15 S. 7th Street, Philadelphia', 4.0),
('Free Library of Philadelphia', 'Public library system with numerous branches throughout the city, including the landmark Central Library.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Free_Library_of_Philadelphia_Front_3008px.jpg/1920px-Free_Library_of_Philadelphia_Front_3008px.jpg', '1901 Vine Street, Philadelphia', 4.5),
('Please Touch Museum', 'Children''s museum offering interactive exhibits and hands-on learning experiences.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/MemorialHallPhila03.jpg/1920px-MemorialHallPhila03.jpg', '4231 Avenue of the Republic, Philadelphia', 4.5),
('Philadelphia Zoo', 'One of the nation''s oldest zoos, featuring a diverse collection of animals and educational exhibits.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/PhilaFlamingos1.JPG/1920px-PhilaFlamingos1.JPG', '3400 W. Girard Avenue, Philadelphia', 4.5),
('Clark Park', 'Public park offering green space, playgrounds, and community events.', 'https://upload.wikimedia.org/wikipedia/commons/3/37/Shakespeare_in_Clark_Park.jpg', '4300-4398 Baltimore Avenue, Philadelphia', 5.0),
('Fairmount Park', 'Sprawling urban park system offering recreational activities and historic landmarks.', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Belmont_Plateau.jpg', 'Along the Schuylkill River, Philadelphia', 4.5),
('Franklin Square', 'Public park and family entertainment center featuring a carousel, mini-golf course, and picnic areas.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/2013_Franklin_Square_Fountain.jpg/1920px-2013_Franklin_Square_Fountain.jpg', '200 N. Sixth Street, Philadelphia', 4.0),
('Logan Circle', 'Historic traffic circle and green space surrounded by cultural institutions and landmarks.', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Logan_Circle_%28Philadelphia%29_crop.JPG', '200 N 19th St, Philadelphia', 4.0),
('Love Park', 'Iconic public plaza famous for its "LOVE" sculpture by Robert Indiana.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Love_Statue%2C_Philadelphia.jpg/1920px-Love_Statue%2C_Philadelphia.jpg', '1599 John F. Kennedy Blvd, Philadelphia', 4.0),
('Penn''s Landing', 'Waterfront area along the Delaware River featuring parks, entertainment venues, and seasonal events.', 'https://upload.wikimedia.org/wikipedia/commons/6/60/Penn%27s_Landing_general_view.jpg', '101 N. Columbus Blvd. Philadelphia', 4.0),
('Rittenhouse Square', 'Charming urban park surrounded by upscale shops, restaurants, and historic buildings.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Rittenhouse_Square_-_autumn_-_IMG_6570.JPG/1920px-Rittenhouse_Square_-_autumn_-_IMG_6570.JPG', 'Center City neighborhood, Philadelphia', 4.5),
('Washington Square', 'Historic public park featuring monuments and green space.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Washington_Square_2018.jpg/1920px-Washington_Square_2018.jpg', '210 W. Washington Square, Philadelphia', 4.0),
('Walnut Street Theatre', 'Historic theater known as the oldest continuously operating theater in the English-speaking world.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Walnut_Street_Theatre_from_east.jpg/1920px-Walnut_Street_Theatre_from_east.jpg', '825 Walnut Street, Philadelphia', 4.5),
('Chinatown', 'Vibrant neighborhood featuring authentic Asian cuisine, cultural events, and shops.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Friendship_Gate_Chinatown_Philadelphia_from_east.jpg/1920px-Friendship_Gate_Chinatown_Philadelphia_from_east.jpg', '19107, Philadelphia', 3.5),
('Fashion District Philadelphia', 'Shopping and entertainment complex offering retail stores, dining options, and entertainment venues.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Fashion_District_Philadelphia_entrance_at_9th_Street_and_Market_Street.jpeg/1920px-Fashion_District_Philadelphia_entrance_at_9th_Street_and_Market_Street.jpeg', '901 Market Street, Philadelphia', 2.5),
('Italian Market', 'Historic outdoor market known for its diverse array of fresh produce and specialty foods.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Phila-dibrunobros.jpg/1920px-Phila-dibrunobros.jpg', 'Along 9th Street, South Philadelphia', 4.0),
('Reading Terminal Market', 'Bustling food market offering a wide variety of culinary delights and fresh produce.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Reading_Terminal_Market_center_court.jpg/1920px-Reading_Terminal_Market_center_court.jpg', '1136 Arch Street, Philadelphia', 4.5),
('Citizens Bank Park', 'Major League Baseball stadium, home to the Philadelphia Phillies.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/CBP2023.jpg/1920px-CBP2023.jpg', '1 Citizens Bank Way, Philadelphia', 4.5),
('Lincoln Financial Field', 'Stadium serving as the home stadium for the Philadelphia Eagles of the NFL.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Lincoln_Financial_Field_%28Aerial_view%29.jpg/1920px-Lincoln_Financial_Field_%28Aerial_view%29.jpg', '1 Lincoln Financial Field Way, Philadelphia', 4.0),
('Wells Fargo Center', 'Multi-purpose arena hosting sports events, concerts, and other entertainment.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Wells_Fargo_Center_-_2019_OWL_Grand_Finals.jpg/1920px-Wells_Fargo_Center_-_2019_OWL_Grand_Finals.jpg', '3601 S. Broad Street, Philadelphia', 4.0);
